versions
version107: spec
	<version: '1.0.7' imports: #('1.0-baseline' )>

	spec for: #'common' do: [
		spec blessing: #'development'.
		spec description: '1.0.7 : Thanks Sean!!!
		
		
Name: MemoryMonitor-SeanDeNigris.15
Author: SeanDeNigris
Time: 22 December 2014, 9:05:37.019012 pm
UUID: 472400a4-6b09-4581-aaee-ddf96531a9a9
Ancestors: MemoryMonitor-AlexandreBergel.14

Fix MemoryMonitor layout to work on Pharo 3.0 and 4.0'.
		spec author: 'AlexandreBergel'.
		spec timestamp: '12/23/2014 13:29'.
		spec package: 'MemoryMonitor' with: 'MemoryMonitor-SeanDeNigris.15'. ].
